### ISSUE TITLE
Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by damonsu** [palmerc/SecureWebSockets#11]
Hello,
when i use your library with wss, i get the error "Trust anchor for certification path not found". Should we also put certificate file in your library?

Thx.

**Comment by palmerc** [comment]
Your certificate is probably not installed correctly. Always check with an SSL Certificate Installation validation tool like [https://search.thawte.com/support/ssl-digital-certificates/index?page=content&id=SO9555](Thawte's SSL Installation Checker)
