### ISSUE TITLE
WSS Websocket

### ISSUE THREAD

**Issue by Grozny** [palmerc/SecureWebSockets#17]
I am trying to use the lib with wss but i always received "Server error 403 (FORBIDDEN).
Where can i get to understand where is the problem.
Help me, please.

**Comment by BackPackerDz** [comment]
Do you add INTERNET permission in your AndroidManifest ?

**Comment by palmerc** [comment]
As found in the included example:
<uses-permission android:name="android.permission.INTERNET"/>

Check under app/src/main/ and you'll find the manifest.
